### ISSUE TITLE
Windows 10 Issue? DUSK_HEADLESS_DISABLED is not recognized

### ISSUE THREAD

**Issue by tjhunkin** [magic-test/magic-test-laravel#10]
If I run "php artisan magic" on windows, I'm getting the following error:

Your Magic Test session is starting...
'DUSK_HEADLESS_DISABLED' is not recognized as an internal or external command, operable program or batch file.

I see the command is trying to shell_exec:
DUSK_HEADLESS_DISABLED=1 MAGIC_TEST=1 php artisan dusk

**Comment by mateusjatenee** [comment]
@tjhunkin Do you have any idea on how to set an env var before running a command on Windows? I sadly don't have a machine to test.

**Comment by mateusjatenee** [comment]
@tjhunkin let me know if `0.2.1` fixes this issue for you.

**Comment by tjhunkin** [comment]
I don't seem to get any more errors, thanks
