### ISSUE TITLE
When app.debug is false, MagicTest crashes

### ISSUE THREAD

**Issue by ThomasLaveto** [magic-test/magic-test-laravel#30]
https://github.com/magic-test/magic-test-laravel/blob/b1d9d22951da5de941c3f65cfff9d9e1fcf34078/src/MagicTest.php#L38

When setting APP_DEBUG=false in my .env, MagicTest crashes on the above line of code. Looks like it could be fixed by replacing `self::minify($scripts)` with `self::minify($script)` (removing the last 's' of the variable name). 

Can someone confirm that this would be the needed fix? Or, am I missing something :)

**Comment by ThomasLaveto** [comment]
This was fixed by #31.

@mateusjatenee Do you think this is worth making a release/ tag for?

**Comment by mateusjatenee** [comment]
@ThomasLaveto Hey Thomas -- apologies for the delay on this. It seems I'm not getting notifications for this repo... I'll tag a release

**Comment by ThomasLaveto** [comment]
No problem, thank you!
