### ISSUE TITLE
Unclear instructions

### ISSUE THREAD

**Issue by sardar1592** [magic-test/magic-test-laravel#44]
Below the line: 

Then, add the following line to your $middleware array under app/Http/Kernel.php:

There is nothing in the docs on github.

**Comment by ITMobilityControl** [comment]
The following code was probably accidentally removed in the latest commit:

```php
\MagicTest\MagicTest\Middleware\MagicTestMiddleware::class
```

**Comment by ITMobilityControl** [comment]
Seems like they inject it with:
```
$this->app['router']->pushMiddlewareToGroup('web', MagicTestMiddleware::class);
```
So this isn't necessary anymore.

**Comment by mateusjatenee** [comment]
You're correct. It no longer requires you to add a middleware :-)
